export default (data, params) => {
  /**
   * https://yuque.antfin.com/docs/share/87ce5e8d-d0bc-4f44-94ad-ef89eeac92df?#
   */
  const { type } = params;
  if (type === 'find-hops') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'pmuens',
          node_id: 'MDQ6VXNlcjE2MDYwMDQ=',
          avatar_url: 'https://avatars.githubusercontent.com/u/1606004?v=4',
          name: 'Philipp Muens',
          company: '@CelsiusNetwork',
          email: 'raute1337@gmx.de',
          location: 'San Francisco, CA',
          hireable: null,
          created_at: '2012-04-02T20:20:41Z',
          type: 'User',
        },
        { id: 'tensorflow', type: 'Repository', name: 'tensorflow', stargazers_count: 158048 },
      ],
      edges: [
        { source: 'xiaosuo', target: 'pmuens', type: 'Following' },
        { source: 'pmuens', target: 'tensorflow', type: 'Starred' },
      ],
    };
  }
  if (type === 'find-common-nbrs') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'pmuens',
          node_id: 'MDQ6VXNlcjE2MDYwMDQ=',
          avatar_url: 'https://avatars.githubusercontent.com/u/1606004?v=4',
          name: 'Philipp Muens',
          company: '@CelsiusNetwork',
          email: 'raute1337@gmx.de',
          location: 'San Francisco, CA',
          hireable: null,
          created_at: '2012-04-02T20:20:41Z',
          type: 'User',
        },
        {
          id: 'veris-pr',
          node_id: 'MDQ6VXNlcjQwNTYzODU1',
          avatar_url: 'https://avatars.githubusercontent.com/u/40563855?v=4',
          name: 'Peeyush Raj',
          company: 'DigiCred',
          email: null,
          location: null,
          hireable: null,
          created_at: '2018-06-25T09:40:31Z',
          type: 'User',
        },
        {
          id: 'mbrukman',
          node_id: 'MDQ6VXNlcjQwNzQ2NTk=',
          avatar_url: 'https://avatars.githubusercontent.com/u/4074659?v=4',
          name: 'Misha Brukman',
          company: '@Google',
          email: null,
          location: null,
          hireable: null,
          created_at: '2013-04-06T03:23:23Z',
          type: 'User',
        },
      ],
      edges: [
        { source: 'xiaosuo', target: 'pmuens', type: 'Following' },
        { source: 'xiaosuo', target: 'mbrukman', type: 'Following' },
        { source: 'veris-pr', target: 'pmuens', type: 'Following' },
        { source: 'veris-pr', target: 'mbrukman', type: 'Following' },
      ],
    };
  }
  if (type == 'find-common-stars') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'veris-pr',
          node_id: 'MDQ6VXNlcjQwNTYzODU1',
          avatar_url: 'https://avatars.githubusercontent.com/u/40563855?v=4',
          name: 'Peeyush Raj',
          company: 'DigiCred',
          email: null,
          location: null,
          hireable: null,
          created_at: '2018-06-25T09:40:31Z',
          type: 'User',
        },
        { id: 'arrow', type: 'Repository', name: 'arrow', stargazers_count: 8241 },
        { id: 'etcd', type: 'Repository', name: 'etcd', stargazers_count: 36839 },
        { id: 'graphscope', type: 'Repository', name: 'graphscope', stargazers_count: 883 },
        { id: 'mysql', type: 'Repository', name: 'mysql', stargazers_count: 6782 },
        { id: 'numpy', type: 'Repository', name: 'numpy', stargazers_count: 17885 },
        { id: 'pandas', type: 'Repository', name: 'pandas', stargazers_count: 30638 },
        { id: 'pytorch', type: 'Repository', name: 'pytorch', stargazers_count: 50009 },
        { id: 'tikv', type: 'Repository', name: 'tikv', stargazers_count: 9698 },
      ],
      edges: [
        { source: 'xiaosuo', target: 'arrow', type: 'Starred' },
        { source: 'xiaosuo', target: 'etcd', type: 'Starred' },
        { source: 'xiaosuo', target: 'graphscope', type: 'Starred' },
        { source: 'xiaosuo', target: 'mysql', type: 'Starred' },
        { source: 'xiaosuo', target: 'numpy', type: 'Starred' },
        { source: 'xiaosuo', target: 'pandas', type: 'Starred' },
        { source: 'xiaosuo', target: 'pytorch', type: 'Starred' },
        { source: 'xiaosuo', target: 'tikv', type: 'Starred' },
        { source: 'veris-pr', target: 'arrow', type: 'Starred' },
        { source: 'veris-pr', target: 'etcd', type: 'Starred' },
        { source: 'veris-pr', target: 'graphscope', type: 'Starred' },
        { source: 'veris-pr', target: 'mysql', type: 'Starred' },
        { source: 'veris-pr', target: 'numpy', type: 'Starred' },
        { source: 'veris-pr', target: 'pandas', type: 'Starred' },
        { source: 'veris-pr', target: 'pytorch', type: 'Starred' },
        { source: 'veris-pr', target: 'tikv', type: 'Starred' },
      ],
    };
  }
  if (type === 'find-same-company') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'salamer',
          node_id: 'MDQ6VXNlcjExMTgyMTg1',
          avatar_url: 'https://avatars.githubusercontent.com/u/11182185?v=4',
          name: 'aljun',
          company: '@bytedance',
          email: 'salameryy@163.com',
          location: 'Beijing',
          hireable: true,
          created_at: '2015-02-24T19:53:34Z',
          type: 'User',
        },
        { id: 'graphscope', type: 'Repository', name: 'graphscope', stargazers_count: 883 },
      ],
      edges: [
        { source: 'xiaosuo', target: 'graphscope', type: 'Starred' },
        { source: 'salamer', target: 'graphscope', type: 'Starred' },
      ],
    };
  }
  if (type === 'find-same-location') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'stanzhai',
          node_id: 'MDQ6VXNlcjE0Mzg3NTc=',
          avatar_url: 'https://avatars.githubusercontent.com/u/1438757?v=4',
          name: 'Stan Zhai',
          company: 'Haizhi Holding Inc.',
          email: 'mail@stanzhai.site',
          location: 'Beijing, China',
          hireable: true,
          created_at: '2012-02-15T04:47:20Z',
          type: 'User',
        },
        {
          id: 'yecol',
          node_id: 'MDQ6VXNlcjQyNjQ2Mw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/426463?v=4',
          name: 'Jingbo Xu',
          company: '@alibaba',
          email: 'xujb1987@gmail.com',
          location: 'Beijing, China.',
          hireable: null,
          created_at: '2010-10-04T13:12:24Z',
          type: 'User',
        },
        {
          id: 'yibit',
          node_id: 'MDQ6VXNlcjgyNTM1MzA=',
          avatar_url: 'https://avatars.githubusercontent.com/u/8253530?v=4',
          name: 'yibit',
          company: 'yibit',
          email: 'yibitx@126.com',
          location: 'BeiJing, China',
          hireable: null,
          created_at: '2014-07-24T05:51:33Z',
          type: 'User',
        },
        { id: 'graphscope', type: 'Repository', name: 'graphscope', stargazers_count: 883 },
      ],
      edges: [
        { source: 'xiaosuo', target: 'graphscope', type: 'Starred' },
        { source: 'yecol', target: 'graphscope', type: 'Starred' },
        { source: 'stanzhai', target: 'graphscope', type: 'Starred' },
        { source: 'yibit', target: 'graphscope', type: 'Starred' },
      ],
    };
  }
  if (type === 'find-earlier-users') {
    return {
      nodes: [
        {
          id: 'xiaosuo',
          node_id: 'MDQ6VXNlcjEwNTAzMw==',
          avatar_url: 'https://avatars.githubusercontent.com/u/105033?v=4',
          name: 'Changli Gao',
          company: '@bytedance ',
          email: 'xiaosuo@gmail.com',
          location: 'Beijing China',
          hireable: null,
          created_at: '2009-07-15T01:50:34Z',
          type: 'User',
        },
        {
          id: 'savage69kr',
          node_id: 'MDQ6VXNlcjU0MjA4',
          avatar_url: 'https://avatars.githubusercontent.com/u/54208?v=4',
          name: 'Joohun, Maeng',
          company: null,
          email: 'savage69kr@gmail.com',
          location: null,
          hireable: null,
          created_at: '2009-02-13T08:32:53Z',
          type: 'User',
        },
        {
          id: 'piggybox',
          node_id: 'MDQ6VXNlcjU0MTQw',
          avatar_url: 'https://avatars.githubusercontent.com/u/54140?v=4',
          name: 'Sky Yin',
          company: null,
          email: 'sky.yin@gmail.com',
          location: 'SF Bay area',
          hireable: null,
          created_at: '2009-02-13T02:35:15Z',
          type: 'User',
        },
        {
          id: 'jits',
          node_id: 'MDQ6VXNlcjMxOTcz',
          avatar_url: 'https://avatars.githubusercontent.com/u/31973?v=4',
          name: 'Jiten (Jits) Bhagat',
          company: null,
          email: null,
          location: 'Brighton & London, UK',
          hireable: null,
          created_at: '2008-10-31T10:32:18Z',
          type: 'User',
        },
        {
          id: 'nikolay',
          node_id: 'MDQ6VXNlcjI4ODI=',
          avatar_url: 'https://avatars.githubusercontent.com/u/2882?v=4',
          name: 'Nikolay Kolev',
          company: '@thestormforge',
          email: null,
          location: 'Irvine, CA, US',
          hireable: true,
          created_at: '2008-03-12T02:45:38Z',
          type: 'User',
        },
        {
          id: 'mrluanma',
          node_id: 'MDQ6VXNlcjM4NTY=',
          avatar_url: 'https://avatars.githubusercontent.com/u/3856?v=4',
          name: 'Zhao Xiaohong',
          company: null,
          email: 'mrluanma@gmail.com',
          location: 'Shanghai, China',
          hireable: true,
          created_at: '2008-03-26T02:00:19Z',
          type: 'User',
        },
        { id: 'graphscope', type: 'Repository', name: 'graphscope', stargazers_count: 883 },
      ],
      edges: [
        { source: 'xiaosuo', target: 'graphscope', type: 'Starred' },
        { source: 'savage69kr', target: 'graphscope', type: 'Starred' },
        { source: 'piggybox', target: 'graphscope', type: 'Starred' },
        { source: 'jits', target: 'graphscope', type: 'Starred' },
        { source: 'nikolay', target: 'graphscope', type: 'Starred' },
        { source: 'mrluanma', target: 'graphscope', type: 'Starred' },
      ],
    };
  }
  return {
    nodes: [],
    edges: [],
  };
};
